---
- name: Include macOS opencode tasks
  ansible.builtin.include_tasks: macos.yml
  when: "'macos' in group_names"

- name: Include Linux opencode tasks
  ansible.builtin.include_tasks: linux.yml
  when: "'macos' not in group_names"

- name: Stow opencode config
  ansible.builtin.command: stow -R opencode
  args:
    chdir: "{{ dotfiles_dir }}"
  register: stow_opencode
  changed_when: stow_opencode.rc == 0
  failed_when: stow_opencode.rc != 0
