---
brew_taps: []

common_packages:
  - fastfetch
  - git
  - git-lfs
  - neovim
  - ripgrep
  - stow
  - tmux
  - wget

brew_casks:
  - legcord
  - font-jetbrains-mono-nerd-font

flameshot_cask: flameshot
google_chrome_cask: google-chrome
ghostty_cask: ghostty

dev_tool_packages:
  - go
  - node
  - python
  - pipx
  - rust
  - starship
  - uv

docker_cask: orbstack
