---
- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload
  become: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Reload udev
  ansible.builtin.command: udevadm control --reload
  become: true

- name: Restart Waydroid Docker firewall
  ansible.builtin.command: systemctl try-restart waydroid-docker-firewall
  changed_when: false
  become: true
