---
- name: Check if Google Chrome is installed
  ansible.builtin.command: which google-chrome
  register: chrome_check
  changed_when: false
  failed_when: false

- name: Import Google Linux signing key
  ansible.builtin.rpm_key:
    key: https://dl.google.com/linux/linux_signing_key.pub
    state: present
  become: true
  when: chrome_check.rc != 0

- name: Install Google Chrome (Fedora)
  ansible.builtin.dnf:
    name: "{{ chrome_url }}"
    state: present
  become: true
  when: chrome_check.rc != 0
